### ISSUE TITLE
Need a guide

### ISSUE THREAD

**Issue by sunnypatel165** [prblaes/ImageColorization#1]
Hi, This is an awesome and brilliant concept.

I was exploring your code and found difficulties in running it. Can you please provide a small guide just to explain how to go about running this code? i mean files are to be run in which order and what all is expected etc?

Please revert back soon so that i can see a demo of your code.
I would like to see how it works for some images and then customize it. So just need to understand the basic workflow for images(not videos yet). 
Thanks

**Comment by pranav54321** [comment]
And also, the mpi4py and gcopy doesn't seem to work well, please provide the appropriate details if possible.

**Comment by sunnypatel165** [comment]
Okay i have figured it out. I dont mind writing a better ReadMe or a proper guide. Would you like a Pull Request?
Thanks again, great project.
